### ISSUE TITLE
Slot #1 

### ISSUE THREAD

**Issue by Whatupdays** [mooreatv/DynamicBoxer#36]
My Slot 1 doesn't recognize or get recognized but my other slots. It use to work but now it doesn't after a update the other day. But now I can't get it working even after going back versions and reinstalling it from scratch. It was a awesome add-on while it worked for me.

**Comment by mooreatv** [comment]
@Whatupdays first, thank you for trying dynamicboxer, and thank you for filling an issue !

can you confirm which version you are using (1.8.1 I assume) ?

any chance you can tell me what you see on the screen for slot 1 and say slot 2 (sshot if you want of the chat window)

any orange or red messages ? any blue ones ?

try this:
broadcast /dbox init  and ctrl-c ctrl-v enter
to reset everything and tell me if that fixed it, if not what happens when you do this

**Comment by mooreatv** [comment]
also reach me on discord or battle net if you need help
https://discord.gg/8Xsk8fu

**Comment by mooreatv** [comment]
if `/dbox init` isn't enough (but I'd like to know why/what happens) you can also broadcast `/dbox reset all` and `/reload`

**Comment by mooreatv** [comment]
@Whatupdays  ping :)

**Comment by mooreatv** [comment]
resolved on discord (though what happened is still a bit of a mystery)

**Comment by mooreatv** [comment]
Seems this may be that in some case (tbd) /1 (the 1. channel) doesn't show up
and DynamicBoxer tries to be nice and wait for /1 before joining the channel


we should probably have a timeout/max wait on that
